### ISSUE TITLE
GopherCon banner gets blocked by many ad blockers

### ISSUE THREAD

**Issue by joncalhoun** [gopheracademy/gopheracademy-web#206]
I have an ad blocker installed because many sites are just insanely obnoxious with their ads. The banner ad at the top of gopher academy obnoxious at all, so I don't mind seeing it and I suspect most others don't either, but it gets blocked by most ad blockers.

I suspect this happens because of the file name - `gc-banner-ad.png`. Would you be opposed to a PR changing that name if it helped with this?

**Comment by erikstmartin** [comment]
Yeah, we only use that space to let people know the conference tickets are available. I think we forgot to take it down... oops

PR would be great 👍
