### ISSUE TITLE
Page titles

### ISSUE THREAD

**Issue by jbub** [gopheracademy/gopheracademy-web#249]
Currently there is always `GopherAcademy - Conferences, Training, and Community` in the page `<title>`. This probably hurts SEO but for me its bad user experience. For example i am using Pocket to save articles and i always get the same page title for every article.

This is hardcoded in the theme:
https://github.com/gopheracademy/gopheracademy-web/blob/master/themes/gaweb/layouts/_default/single.html#L13

**Comment by bketelsen** [comment]
fixed, will deploy shortly

**Comment by jbub** [comment]
Wonderful! Thank you!
