### ISSUE TITLE
searchbox not working

### ISSUE THREAD

**Issue by gbbr** [gopheracademy/gopheracademy-web#28]
Search box doesn't search correctly and "magnifying glass" icon doesn't work

**Comment by rahmanm12** [comment]
Bought the full licensed version of SearchBlox. After adding 4 HTTP collections, we can not any other collection!! When we try to add it says, collection successfully added but it's not. 

Restarted SearchBlox but could not fix the problem. Anybody has any idea?

**Comment by davecheney** [comment]
This isn't the issue you are looking for.
